# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - healthcare-network

  nginx:
    image: nginx:alpine
    container_name: healthcare-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - healthcare-network

  db:
    image: mysql:8.0
    container_name: healthcare-db
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - healthcare-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

volumes:
  healthcare-mysql:
    driver: local